

services:

  gpu:
    image: moveit/moveit2:main-jazzy-tutorial-source
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moveit2_container_demo_2
    privileged: true
    network_mode: host
    ipc: host
    # privileged: true
    stdin_open: true
    restart: unless-stopped
    # command: /bin/bash
    # # tty: true
    # # stdin_open: true
    devices:
      - /dev/video0:/dev/video0        # ← ADD HERE (same level as 'deploy')

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority

      
      # - /home/nirbhayborikar/framework/demotest_moveitServo_kinova_gen3/rso2_ws/src/volume:/root/volume
      #- /home/nirbhayborikar/framework/demotest_moveitServo_kinova_gen3/rso2_ws/src/volume:/root/ws_moveit/src/volume
      # - /home/nirbhayborikar/framework/demotest_moveitServo_kinova_gen3/rso2_ws/src/volume/kortex_servo_gen3:/root/ws_moveit/src/kortex_servo_gen3
      - ../src/kortex/ros2_ws/src:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/kortex/ros2_ws/src
      - ../src/volume/kortex_servo_gen3/launch/servo_kinovagen3.launch.py:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/launch/servo_kinovagen3.launch.py
      - ../src/volume/kortex_servo_gen3/config/gen3_servo.yaml:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config/gen3_servo.yaml
      - ../src/kortex/ros2_ws/src/iki_kortex_moveit_config/config/kortex.srdf:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config/kortex.srdf
      - ../src/kortex/ros2_ws/src/iki_kortex_moveit_config/config/joint_limits.yaml:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config/joint_limits.yaml
      - ../src/kortex/ros2_ws/src/iki_kortex_moveit_config/config/kinematics.yaml:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config/kinematics.yaml
      - ../src/kortex/iki_kortex_description/urdf_xarco/kortex_standalone.urdf.xarco:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/kortex/ros2_ws/src/iki_kortex_description/urdf_xacro/
      - ../src/kortex/ros2_ws/src/iki_kortex_description/config/initial_positions.yaml:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config/initial_positions.yaml
      # - /home/nirbhayborikar/framework/demotest_moveitServo_kinova_gen3/rso2_ws/src/volume/kortex_servo_gen3/config:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config
      - ../src/kortex/ros2_ws/src/iki_kortex_moveit_config/config/ros2_controllers.yaml:/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/config/ros2_controllers.yaml
   

   #/root/ws_moveit/src/moveit2/moveit_ros/moveit_servo/kortex/ros2_ws/src/iki_kortex_description/urdf_xacro/kortex_standalone.urdf.xacro
    command:
      - bash
      - -c
      - |
        source /opt/ros/jazzy/setup.bash &&
        pwd &&

        cd ~/ws_moveit/src/moveit2/moveit_ros/moveit_servo/kortex/ros2_ws/ &&
        

        #colcon build --packages-select iki_kortex_description &&
        #colcon build --packages-select robotiq_description &&
        #colcon build --packages-select servo_keyboard_kinova &&
        #colcon build --packages-select kortex_description &&
        #colcon build --packages-select sensagram_teleop &&
        #colcon build --packages-select olive_imu_control &&
        #colcon build --packages-select mediapipe &&
        colcon build --packages-select kinova_gen3_teleop &&

        source install/setup.bash &&
        ros2 launch kinova_gen3_teleop teleop.launch.py
        cd ~/ws_moveit/ &&
        #colcon build --packages-up-to moveit_servo 2>&1 | tail -50 &&
        #colcon build --packages-select moveit_servo &&
        #source ~/ws_moveit/install/setup.bash &&
        #ros2 run moveit_servo servo_node &&
        #ros2 launch moveit_servo servo_kinovagen3.launch.py &&
        #ros2 launch sensagram_teleop teleop.launch.py &&
        #ros2 run sensagram_teleop servo_teleop_node &&
        #ros2 launch olive_imu_teleop olive_imu_teleop.launch.py
        #ros2 topic pub --once /joint_trajectory_controller/joint_trajectory trajectory_msgs/msg/JointTrajectory "{joint_names: ['joint_1','joint_2','joint_3','joint_4','joint_5','joint_6','joint_7'], points: [{positions: [0.0,1.0,1.57,-1.57,0.0,1.0,0.0], time_from_start: {sec: 5}}]}"
        #ros2 launch olive_imu_control olive_teleop.launch.py
        #ros2 topic echo /servo_node/delta_twist_cmds #MONITOR

                



   
    environment:
      ROS_DOMAIN_ID: 145
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_AUTOMATIC_DISCOVERY_RANGE: "LOCALHOST"
      # RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      # FASTDDS_DEFAULT_PROFILES_FILE: /home/nirbhayborikar/framework/demotest_moveitServo_kinova_gen3/rso2_ws/src/volume/fastdds.xml



#ros2 param get /servo_node moveit_servo.lower_singularity_threshold    (check gen3_servo.yaml changing or not )



# ros2 param get /servo_node moveit_servo.lower_singularity_threshold


#colcon build --packages-select kinova_gen3_teleop