#####################the main #####################

# servo_node:
#   ros__parameters:

#     publish_period: 0.01
#     max_expected_latency: 0.1

#     command_in_type: "speed_units"

#     scale:
#       linear: 0.2    # 0.2
#       rotational: 0.1 # slow rotation
#       joint: 0.15 

#     publish_joint_positions: true
#     publish_joint_velocities: true
#     publish_joint_accelerations: false

#     use_smoothing: true
#     smoothing_filter_plugin_name: "online_signal_smoothing::AccelerationLimitedPlugin"

#     is_primary_planning_scene_monitor: true
#     check_octomap_collisions: false

#     move_group_name: manipulator


#     # ========== AGGRESSIVE SINGULARITY PROTECTION ==========
#     lower_singularity_threshold: 17.0 # 10.0  riase to 17


#     hard_stop_singularity_threshold: 50.0 # lower from 50 to 60
#     leaving_singularity_threshold_multiplier: 2.0

#   # ========== LARGE JOINT MARGINS ==========

#     # ── JOINT LIMITS ─────────────────────────────
#     # Per-joint margins for Gen3 6DOF
#     # joint_1,4,6 = continuous → give 0.0 (no limit to protect)
#     # joint_2,3,5 = have limits → give 0.15 rad buffer

#   # Large margins = stop far from joint limits (safe)
#     #joint_limit_margins: [0.2] # 0.12

#     #joint_limit_margins: [0.0, 0.15, 0.15, 0.0, 0.15, 0.0, 0.0]
#     joint_limit_margins: [0.1, 0.2, 0.25, 0.15, 0.2, 0.15, 0.0]
    
#     #                    j1    j2    j3    j4   j5    j6    j7

#     # new added
#     #joint_limit_margins: [0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]
#      #

#     cartesian_command_in_topic: servo_node/delta_twist_cmds
#     joint_command_in_topic: servo_node/delta_joint_cmds
#     joint_topic: /joint_states
#     status_topic: ~/status

# # ========== OUTPUT ==========
#     command_out_type: trajectory_msgs/JointTrajectory
#     command_out_topic: /joint_trajectory_controller/joint_trajectory



#     # ========== OTHER SAFETY ==========
#     check_collisions: true
#     collision_check_rate: 10.0


#     self_collision_proximity_threshold: 0.01
#     scene_collision_proximity_threshold: 0.02
#############################the above manin ################


servo_node:
  ros__parameters:
    publish_period: 0.01
    max_expected_latency: 0.1
    command_in_type: "speed_units"
    
    scale:
      linear: 0.2 # 0.15
      rotational: 0.2
      joint: 0.2
    
    publish_joint_positions: true
    publish_joint_velocities: true
    publish_joint_accelerations: false
    
    use_smoothing: true
    smoothing_filter_plugin_name: "online_signal_smoothing::AccelerationLimitedPlugin"
    
    is_primary_planning_scene_monitor: true
    check_octomap_collisions: false
    move_group_name: manipulator
    
    # ========== SINGULARITY ==========
    lower_singularity_threshold: 8.0 # lower =lesss strict #15.0
    hard_stop_singularity_threshold: 20.0 # lower =lesss strict  #30.0
    leaving_singularity_threshold_multiplier: 5.0 # #3.0 higher = easier escape 
    
    # ========== JOINT LIMITS ==========
    # joint_limit_margins: [0.1, 0.2, 0.25, 0.15, 0.2, 0.15, 0.1]
    joint_limit_margins: [0.05, 0.15, 0.2, 0.15, 0.15, 0.05, 0.05] # 6-->0.1-->0.05 , as it is wrist joint 


    # ========== TOPICS ==========
    cartesian_command_in_topic: servo_node/delta_twist_cmds
    joint_command_in_topic: servo_node/delta_joint_cmds
    joint_topic: /joint_states
    status_topic: ~/status
    command_out_type: trajectory_msgs/JointTrajectory
    command_out_topic: /joint_trajectory_controller/joint_trajectory
    
    # ========== COLLISION ==========
    check_collisions: true
    collision_check_rate: 10.0
    self_collision_proximity_threshold: 0.01
    scene_collision_proximity_threshold: 0.02
    
    # ========== SAFETY ==========new added
    halt_all_joints_in_joint_mode: false
    halt_all_joints_in_cartesian_mode: false
    override_velocity_scaling_factor: 0.8