image: docker:latest

stages:
  - docker

build_docker_image:
  stage: docker
  tags:
    - image-build
  script:
    - git submodule update --init --recursive #update submodules
    - docker build -t fbe-dockerreg.rwu.de/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:jazzy -f docker/Dockerfile .
    - docker push fbe-dockerreg.rwu.de/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:jazzy
