# Default initial positions for kortex's ros2_control fake system

initial_positions:
  finger_joint: 0.0
  joint_1: 0.0
  joint_2: 0.26
  joint_3: 3.14
  joint_4: -2.27
  joint_5: 0.0
  joint_6: 0.96
  joint_7: 1.57